kind: Service
apiVersion: v1
metadata:
  name: wg-socks-service
  namespace: wg-socks
  labels:
    app: wg-socks
spec:
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 1080
      nodePort: 32000
  selector:
    app: wg-socks
  type: NodePort
